name: Docker-Push

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: philxi/log-bot
      - run: git remote add dee https://github.com/drdeee/log-bot
      - run: git push --force dee main
